#!/usr/bin/env python3
"""Compute per-region sun-time analytics for the NZ DST dashboard.

Scenarios:
  keep      — status quo: NZST (UTC+12) winter, NZDT (UTC+13) summer
  abolish   — permanent NZST (UTC+12) all year
  permanent — permanent NZDT (UTC+13) all year

Metrics per region (computed from NOAA solar calculator, representative city):
  winter_sunrise  — sunrise time on the winter solstice (~21 June)
  winter_sunset   — sunset time on the winter solstice
  summer_solstice_sunset — sunset on ~21 Dec
  days_sunrise_after_7   — days/year where sunrise is at or after 07:00
  days_sunset_before_6   — days/year where sunset is before 18:00

All numbers generated by this script; nothing from memory. Representative cities
are the region's largest city (census-based, standard practice for regional sun profiles).
"""
import math, json, datetime

# ---------- NOAA solar calculator (translated to pure python) ----------
def sun_times(date, lat, lon, tz_offset_hours):
    """NOAA spreadsheet algorithm. Returns (sunrise, sunset, solar_noon) as local clock hours."""
    y, m, dd = date.year, date.month, date.day
    if m <= 2:
        y -= 1; m += 12
    A = y // 100
    B = 2 - A + A // 4
    jd = math.floor(365.25 * (y + 4716)) + math.floor(30.6001 * (m + 1)) + dd + B - 1524.5
    doy = date.timetuple().tm_yday
    frac_year = (2 * math.pi / 365.0) * (doy - 1 + (12 - 0.5) / 24.0)
    eqtime = 229.18 * (0.000075 + 0.001868 * math.cos(frac_year) - 0.032077 * math.sin(frac_year)
                       - 0.014615 * math.cos(2 * frac_year) - 0.040849 * math.sin(2 * frac_year))
    decl = (0.006918 - 0.399912 * math.cos(frac_year) + 0.070257 * math.sin(frac_year)
            - 0.006758 * math.cos(2 * frac_year) + 0.000907 * math.sin(2 * frac_year)
            - 0.002697 * math.cos(3 * frac_year) + 0.00148 * math.sin(3 * frac_year))
    cos_ha = (math.cos(math.radians(90.833)) / (math.cos(math.radians(lat)) * math.cos(decl))
              - math.tan(math.radians(lat)) * math.tan(decl))
    if cos_ha < -1 or cos_ha > 1:
        return None, None, None  # polar day/night — not for NZ
    ha = math.degrees(math.acos(cos_ha))
    sunrise_off = eqtime / 60.0 + (4.0 * lon) / 60.0 - tz_offset_hours
    sunrise = 12 - sunrise_off - ha / 15.0
    sunset = 12 - sunrise_off + ha / 15.0
    noon = 12 - sunrise_off
    return sunrise, sunset, noon

def fmt_h(h):
    if h is None:
        return None
    h = (h + 24) % 24
    hh = int(h); mm = int(round((h - hh) * 60))
    if mm == 60: hh += 1; mm = 0
    if hh == 24: hh = 0
    return f"{hh:02d}:{mm:02d}"

# ---------- NZ DST calendar (per Time Act 1974 / current govt.nz schedule) ----------
def is_nzdt(date):
    """NZDT = last Sunday of September 02:00 to first Sunday of April 03:00."""
    y = date.year
    # last Sunday of September
    d = datetime.date(y, 9, 30)
    while d.weekday() != 6:  # Sunday=6
        d -= datetime.timedelta(days=1)
    start = d
    # first Sunday of April
    d = datetime.date(y, 4, 1)
    while d.weekday() != 6:
        d += datetime.timedelta(days=1)
    end = d
    if date >= start:  # late Sept onward: NZDT until next April
        return True
    if date < end:     # Jan 1 to first Sunday of April: still NZDT from previous year's start
        return True
    return False

# ---------- Regions: representative cities (largest city per region) ----------
# city, lat, lon — coordinates of city centers
REGIONS = [
    # (region, city, lat, lon, pop)
    ("Northland", "Whangārei", -35.732, 174.322, 201100),
    ("Auckland", "Auckland", -36.85, 174.76, 1816000),
    ("Waikato", "Hamilton", -37.787, 175.279, 532100),
    ("Bay of Plenty", "Tauranga", -37.686, 176.167, 351500),
    ("Gisborne", "Gisborne", -38.662, 178.018, 52700),
    ("Hawke's Bay", "Napier", -39.493, 176.912, 179700),
    ("Taranaki", "New Plymouth", -39.056, 174.075, 130300),
    ("Manawatū-Whanganui", "Palmerston North", -40.356, 175.611, 260700),
    ("Wellington", "Wellington", -41.287, 174.776, 543400),
    ("Tasman", "Richmond", -41.339, 173.185, 59900),
    ("Nelson", "Nelson", -41.271, 173.284, 54300),
    ("Marlborough", "Blenheim", -41.516, 173.957, 50800),
    ("West Coast", "Greymouth", -42.451, 171.207, 34700),
    ("Canterbury", "Christchurch", -43.531, 172.637, 698200),
    ("Otago", "Dunedin", -45.878, 170.503, 253900),
    ("Southland", "Invercargill", -46.413, 168.354, 104800),
]

# Chatham Islands note (not a region; UTC+12:45/+13:45)
CHATHAMS = {
    "name": "Chatham Islands",
    "note": "Territory, not a region — runs 45 minutes ahead: UTC+12:45 standard, UTC+13:45 daylight.",
    "lat": -43.9, "lon": -176.5,
}

def scenario_offset(date, scenario):
    if scenario == "abolish":
        return 12
    if scenario == "permanent":
        return 13
    return 13 if is_nzdt(date) else 12  # keep

def compute_region(city, lat, lon, pop):
    out = {"city": city, "lat": lat, "lon": lon, "pop": pop, "scenarios": {}}
    for sc in ("keep", "abolish", "permanent"):
        ws = datetime.date(2026, 6, 21)
        ss = datetime.date(2026, 12, 22)
        r_w, s_w, _ = sun_times(ws, lat, lon, scenario_offset(ws, sc))
        r_s, s_s, _ = sun_times(ss, lat, lon, scenario_offset(ss, sc))
        # count days in a full year
        days_s_after_7 = days_s_before_6 = 0
        d = datetime.date(2026, 1, 1)
        end = datetime.date(2026, 12, 31)
        while d <= end:
            tz = scenario_offset(d, sc)
            r, s, _ = sun_times(d, lat, lon, tz)
            if r is not None:
                if r >= 7.0: days_s_after_7 += 1
                if s < 18.0: days_s_before_6 += 1
            d += datetime.timedelta(days=1)
        out["scenarios"][sc] = {
            "winter_sunrise": fmt_h(r_w),
            "winter_sunset": fmt_h(s_w),
            "summer_sunset": fmt_h(s_s),
            "days_sunrise_after_7": days_s_after_7,
            "days_sunset_before_6": days_s_before_6,
        }
    return out

def main():
    result = {"meta": {
        "computed": "2026-09-16",
        "method": "NOAA solar calculator, per-day loop over 2026, NZ DST calendar per Time Act 1974",
        "note_chathams": CHATHAMS["note"],
    }, "regions": {}}
    total_pop = sum(r[4] for r in REGIONS)
    national = {}
    for name, city, lat, lon, pop in REGIONS:
        result["regions"][name] = compute_region(city, lat, lon, pop)
    for sc in ("keep", "abolish", "permanent"):
        w_after7 = sum(result["regions"][r[0]]["scenarios"][sc]["days_sunrise_after_7"] * r[4] for r in REGIONS) / total_pop
        w_before6 = sum(result["regions"][r[0]]["scenarios"][sc]["days_sunset_before_6"] * r[4] for r in REGIONS) / total_pop
        national[sc] = {
            "pop_weighted_days_sunrise_after_7": round(w_after7, 1),
            "pop_weighted_days_sunset_before_6": round(w_before6, 1),
        }
    result["national"] = national
    result["meta"]["total_pop"] = total_pop
    print("national:", json.dumps(national, indent=1))
    with open('/opt/data/dst_dashboard/dst_data.json', 'w') as f:
        json.dump(result, f, indent=1)
    print("wrote dst_data.json")

if __name__ == "__main__":
    main()